server:
  env: "debug"
  address: "127.0.0.1"
  port: 8080
  gracefulShutdownPeriod: 30
  rateLimits:
    - limitType: "server"
      burst: 500
      qps: 100
      cacheSize: 1
    - limitType: "ip"
      burst: 50
      qps: 10
      cacheSize: 2048
  jwtSecret: weaveserver

db:
  type: sqlite
  port: 5432 
  host: "localhost"
  name: "webm"
  user: "postgres"
  password: "123456"
  filename: "webm-store.db"
  migrate: true

revers:
  enable: true
  proxyUrls:
    "/transmission": "http://nas:9091/transmission"

static:
  enable: true
  contents:
    "/": "./web/dist/"
